name: Auto Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  # pull_request_target:

jobs:
  auto-labeler:
    name: Auto Labeler
    runs-on: ubuntu-latest
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
      contents: read

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-releaser: true # releaser mode is disabled.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
